admin_omniva_int_generate_bulk:
  path: /omniva-intk/bulk-generate
  methods: [POST]
  defaults:
    _controller: 'OmnivaInt\Controller\Admin\VenipakBulkActionController::bulkGenerateLabels'

admin_omniva_int_print_bulk:
  path: /omniva-int/bulk-print
  methods: [POST]
  defaults:
    _controller: 'OmnivaInt\Controller\Admin\VenipakBulkActionController::bulkPrintLabels'